// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: proto/dme.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TokenRing_RequestCriticalSection_FullMethodName = "/proto.TokenRing/RequestCriticalSection"
	TokenRing_PassToken_FullMethodName              = "/proto.TokenRing/PassToken"
	TokenRing_RecieveToken_FullMethodName           = "/proto.TokenRing/RecieveToken"
)

// TokenRingClient is the client API for TokenRing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenRingClient interface {
	RequestCriticalSection(ctx context.Context, opts ...grpc.CallOption) (TokenRing_RequestCriticalSectionClient, error)
	PassToken(ctx context.Context, in *TokenMessage, opts ...grpc.CallOption) (*Acknowledge, error)
	RecieveToken(ctx context.Context, in *TokenMessage, opts ...grpc.CallOption) (*Acknowledge, error)
}

type tokenRingClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenRingClient(cc grpc.ClientConnInterface) TokenRingClient {
	return &tokenRingClient{cc}
}

func (c *tokenRingClient) RequestCriticalSection(ctx context.Context, opts ...grpc.CallOption) (TokenRing_RequestCriticalSectionClient, error) {
	stream, err := c.cc.NewStream(ctx, &TokenRing_ServiceDesc.Streams[0], TokenRing_RequestCriticalSection_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tokenRingRequestCriticalSectionClient{stream}
	return x, nil
}

type TokenRing_RequestCriticalSectionClient interface {
	Send(*CriticalSectionRequest) error
	Recv() (*CriticalSectionResponse, error)
	grpc.ClientStream
}

type tokenRingRequestCriticalSectionClient struct {
	grpc.ClientStream
}

func (x *tokenRingRequestCriticalSectionClient) Send(m *CriticalSectionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tokenRingRequestCriticalSectionClient) Recv() (*CriticalSectionResponse, error) {
	m := new(CriticalSectionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tokenRingClient) PassToken(ctx context.Context, in *TokenMessage, opts ...grpc.CallOption) (*Acknowledge, error) {
	out := new(Acknowledge)
	err := c.cc.Invoke(ctx, TokenRing_PassToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenRingClient) RecieveToken(ctx context.Context, in *TokenMessage, opts ...grpc.CallOption) (*Acknowledge, error) {
	out := new(Acknowledge)
	err := c.cc.Invoke(ctx, TokenRing_RecieveToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenRingServer is the server API for TokenRing service.
// All implementations must embed UnimplementedTokenRingServer
// for forward compatibility
type TokenRingServer interface {
	RequestCriticalSection(TokenRing_RequestCriticalSectionServer) error
	PassToken(context.Context, *TokenMessage) (*Acknowledge, error)
	RecieveToken(context.Context, *TokenMessage) (*Acknowledge, error)
	mustEmbedUnimplementedTokenRingServer()
}

// UnimplementedTokenRingServer must be embedded to have forward compatible implementations.
type UnimplementedTokenRingServer struct {
}

func (UnimplementedTokenRingServer) RequestCriticalSection(TokenRing_RequestCriticalSectionServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestCriticalSection not implemented")
}
func (UnimplementedTokenRingServer) PassToken(context.Context, *TokenMessage) (*Acknowledge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassToken not implemented")
}
func (UnimplementedTokenRingServer) RecieveToken(context.Context, *TokenMessage) (*Acknowledge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveToken not implemented")
}
func (UnimplementedTokenRingServer) mustEmbedUnimplementedTokenRingServer() {}

// UnsafeTokenRingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenRingServer will
// result in compilation errors.
type UnsafeTokenRingServer interface {
	mustEmbedUnimplementedTokenRingServer()
}

func RegisterTokenRingServer(s grpc.ServiceRegistrar, srv TokenRingServer) {
	s.RegisterService(&TokenRing_ServiceDesc, srv)
}

func _TokenRing_RequestCriticalSection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TokenRingServer).RequestCriticalSection(&tokenRingRequestCriticalSectionServer{stream})
}

type TokenRing_RequestCriticalSectionServer interface {
	Send(*CriticalSectionResponse) error
	Recv() (*CriticalSectionRequest, error)
	grpc.ServerStream
}

type tokenRingRequestCriticalSectionServer struct {
	grpc.ServerStream
}

func (x *tokenRingRequestCriticalSectionServer) Send(m *CriticalSectionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tokenRingRequestCriticalSectionServer) Recv() (*CriticalSectionRequest, error) {
	m := new(CriticalSectionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TokenRing_PassToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenRingServer).PassToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenRing_PassToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenRingServer).PassToken(ctx, req.(*TokenMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenRing_RecieveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenRingServer).RecieveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenRing_RecieveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenRingServer).RecieveToken(ctx, req.(*TokenMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenRing_ServiceDesc is the grpc.ServiceDesc for TokenRing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenRing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TokenRing",
	HandlerType: (*TokenRingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PassToken",
			Handler:    _TokenRing_PassToken_Handler,
		},
		{
			MethodName: "RecieveToken",
			Handler:    _TokenRing_RecieveToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestCriticalSection",
			Handler:       _TokenRing_RequestCriticalSection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/dme.proto",
}
